spring.sql.init.data-locations=
spring.thymeleaf.prefix=classpath:/templates/
spring.web.resources.static-locations=classpath:/static/
spring.datasource.url=jdbc:postgresql://localhost:5432/unit-billing
spring.datasource.driver-class-name=org.postgresql.Driver