server.port=8080
spring.application.name=unit-billing

spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

spring.messages.basename= i18n/common,i18n/admin,i18n/client,i18n/identity,i18n/catalog,i18n/ledger,i18n/subscribers,i18n/subscriptions, i18n/errors
spring.messages.fallback-to-system-locale=false
spring.messages.encoding=UTF-8
