INSERT INTO application_users (
    first_name,
    last_name,
    email,
    phone,
    password,
    balance,
    country,
    city,
    region,
    street,
    house_number,
    apartment,
    postal_code,
    is_deleted
) VALUES
      (
          'John',
          'Doe',
          'john.doe@example.com',
          '+15550199',
          '$2a$12$wwFwCF6vxcQMZu9QizKZJOPmDaacESu5Od58jdAwv4h6tF7XZ44mC', -- hashed password ("password123")
          500.00,
          'USA',
          'New York',
          'NY',
          'Broadway',
          '100',
          '4B',
          '10001',
          FALSE
      ),
      (
          'Alice',
          'Smith',
          'alice.smith@example.com',
          '+15550188',
          '$2a$12$wwFwCF6vxcQMZu9QizKZJOPmDaacESu5Od58jdAwv4h6tF7XZ44mC',
          1250.50,
          'USA',
          'San Francisco',
          'CA',
          'Market Street',
          '500',
          '12A',
          '94105',
          FALSE
      ),
      (
          'Michael',
          'Johnson',
          'michael.johnson@example.com',
          '+4420794609',
          '$2a$12$wwFwCF6vxcQMZu9QizKZJOPmDaacESu5Od58jdAwv4h6tF7XZ44mC',
          3200.00,
          'United Kingdom',
          'London',
          'Greater London',
          'Baker Street',
          '221',
          'B',
          'NW1 6XE',
          FALSE
      );